using System.Text.Json.Serialization;
using Vex.Modules.Mcp.Models;

namespace Vex.Modules.Mcp.Serialization;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(JsonRpcRequest))]
[JsonSerializable(typeof(JsonRpcResponse))]
[JsonSerializable(typeof(JsonRpcError))]
[JsonSerializable(typeof(McpInitializeResult))]
[JsonSerializable(typeof(McpServerInfo))]
[JsonSerializable(typeof(McpCapabilities))]
[JsonSerializable(typeof(McpToolsCapability))]
[JsonSerializable(typeof(McpToolsListResult))]
[JsonSerializable(typeof(McpToolDescription))]
[JsonSerializable(typeof(McpToolCallParams))]
[JsonSerializable(typeof(McpToolCallResult))]
[JsonSerializable(typeof(McpContentItem))]
[JsonSerializable(typeof(EmptyInput))]
[JsonSerializable(typeof(ReplaceCurrentDocumentInput))]
[JsonSerializable(typeof(ApplyTextEditInput))]
[JsonSerializable(typeof(InsertTextInput))]
[JsonSerializable(typeof(ReplaceSelectionInput))]
[JsonSerializable(typeof(OpenDocumentInput))]
[JsonSerializable(typeof(UiSetThemeInput))]
[JsonSerializable(typeof(UiSetTypographyInput))]
[JsonSerializable(typeof(UiSetLanguageInput))]
[JsonSerializable(typeof(UiSetLayoutInput))]
[JsonSerializable(typeof(UiShowSidebarTabInput))]
[JsonSerializable(typeof(UiOpenPanelInput))]
[JsonSerializable(typeof(UiApplyEditorCommandInput))]
[JsonSerializable(typeof(ExportCurrentDocumentInput))]
[JsonSerializable(typeof(CopyRenderedHtmlInput))]
[JsonSerializable(typeof(CurrentDocumentResult))]
[JsonSerializable(typeof(OutlineResult))]
[JsonSerializable(typeof(OutlineItemResult))]
[JsonSerializable(typeof(SelectionResult))]
[JsonSerializable(typeof(AppStatusResult))]
[JsonSerializable(typeof(UiStateResult))]
[JsonSerializable(typeof(RenderedHtmlResult))]
[JsonSerializable(typeof(OperationResult))]
[JsonSerializable(typeof(OperationAuditResult))]
[JsonSerializable(typeof(McpOperationRecord))]
internal sealed partial class McpJsonContext : JsonSerializerContext;
